### PR TITLE
hacktoberfest contribution

### PR DESCRIPTION
**Pull request by nabeelraza-7**
Looking forward to learning with you. ^_^

### CODE REVIEW

**Review by msaaddev — APPROVED** [review]

**Comment by msaaddev** [comment]
Looks good to me 👌🏻 

BTW @nabeelraza-7 it won't be considered as Hacktoberfest PR since October hasn't started yet.

**Comment by nabeelraza-7** [comment]
This repo is just for practice, right?

**Comment by msaaddev** [comment]
Not entirely. I created this so people who are new to open-source can open a PR here. And that PR will be considered for Hacktoberfest. I am going to use this in the upcoming workshop.

**Comment by nabeelraza-7** [comment]
Okay. :')

**Pull request merged**
